// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: net/proto/agp.proto

package cproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusCode is shared by AGP, HTTP Actor calls and cluster envelopes.
type StatusCode int32

const (
	StatusCode_STATUS_OK                  StatusCode = 0
	StatusCode_STATUS_CANCELLED           StatusCode = 1
	StatusCode_STATUS_INVALID_ARGUMENT    StatusCode = 2
	StatusCode_STATUS_DEADLINE_EXCEEDED   StatusCode = 3
	StatusCode_STATUS_NOT_FOUND           StatusCode = 4
	StatusCode_STATUS_ALREADY_EXISTS      StatusCode = 5
	StatusCode_STATUS_PERMISSION_DENIED   StatusCode = 6
	StatusCode_STATUS_UNAUTHENTICATED     StatusCode = 7
	StatusCode_STATUS_RESOURCE_EXHAUSTED  StatusCode = 8
	StatusCode_STATUS_FAILED_PRECONDITION StatusCode = 9
	StatusCode_STATUS_ABORTED             StatusCode = 10
	StatusCode_STATUS_INTERNAL            StatusCode = 11
	StatusCode_STATUS_UNAVAILABLE         StatusCode = 12
	StatusCode_STATUS_UNSUPPORTED_MEDIA   StatusCode = 13
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:  "STATUS_OK",
		1:  "STATUS_CANCELLED",
		2:  "STATUS_INVALID_ARGUMENT",
		3:  "STATUS_DEADLINE_EXCEEDED",
		4:  "STATUS_NOT_FOUND",
		5:  "STATUS_ALREADY_EXISTS",
		6:  "STATUS_PERMISSION_DENIED",
		7:  "STATUS_UNAUTHENTICATED",
		8:  "STATUS_RESOURCE_EXHAUSTED",
		9:  "STATUS_FAILED_PRECONDITION",
		10: "STATUS_ABORTED",
		11: "STATUS_INTERNAL",
		12: "STATUS_UNAVAILABLE",
		13: "STATUS_UNSUPPORTED_MEDIA",
	}
	StatusCode_value = map[string]int32{
		"STATUS_OK":                  0,
		"STATUS_CANCELLED":           1,
		"STATUS_INVALID_ARGUMENT":    2,
		"STATUS_DEADLINE_EXCEEDED":   3,
		"STATUS_NOT_FOUND":           4,
		"STATUS_ALREADY_EXISTS":      5,
		"STATUS_PERMISSION_DENIED":   6,
		"STATUS_UNAUTHENTICATED":     7,
		"STATUS_RESOURCE_EXHAUSTED":  8,
		"STATUS_FAILED_PRECONDITION": 9,
		"STATUS_ABORTED":             10,
		"STATUS_INTERNAL":            11,
		"STATUS_UNAVAILABLE":         12,
		"STATUS_UNSUPPORTED_MEDIA":   13,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_net_proto_agp_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_net_proto_agp_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{0}
}

// Packet is the complete AGP application frame. The outer frame is always
// protobuf; codec selects only how Request/Response/Notify.body is encoded.
type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Packet_Request
	//	*Packet_Response
	//	*Packet_Notify
	Kind          isPacket_Kind     `protobuf_oneof:"kind"`
	Metadata      map[string][]byte `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Codec         int32             `protobuf:"varint,5,opt,name=codec,proto3" json:"codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_net_proto_agp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetKind() isPacket_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Packet) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Kind.(*Packet_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Packet) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Kind.(*Packet_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Packet) GetNotify() *Notify {
	if x != nil {
		if x, ok := x.Kind.(*Packet_Notify); ok {
			return x.Notify
		}
	}
	return nil
}

func (x *Packet) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Packet) GetCodec() int32 {
	if x != nil {
		return x.Codec
	}
	return 0
}

type isPacket_Kind interface {
	isPacket_Kind()
}

type Packet_Request struct {
	Request *Request `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type Packet_Response struct {
	Response *Response `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type Packet_Notify struct {
	Notify *Notify `protobuf:"bytes,3,opt,name=notify,proto3,oneof"`
}

func (*Packet_Request) isPacket_Kind() {}

func (*Packet_Response) isPacket_Kind() {}

func (*Packet_Notify) isPacket_Kind() {}

// Request expects exactly one Response with the same request_id.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MethodId      uint32                 `protobuf:"varint,2,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_net_proto_agp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Request) GetMethodId() uint32 {
	if x != nil {
		return x.MethodId
	}
	return 0
}

func (x *Request) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Response carries transport status separately from the encoded business body.
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_net_proto_agp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Notify is one-way and never receives a Response.
type Notify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MethodId      uint32                 `protobuf:"varint,1,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notify) Reset() {
	*x = Notify{}
	mi := &file_net_proto_agp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{3}
}

func (x *Notify) GetMethodId() uint32 {
	if x != nil {
		return x.MethodId
	}
	return 0
}

func (x *Notify) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// HandshakeRequest negotiates the highest protocol version supported by both ends.
type HandshakeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SupportedVersions []uint32               `protobuf:"varint,1,rep,packed,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_net_proto_agp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{4}
}

func (x *HandshakeRequest) GetSupportedVersions() []uint32 {
	if x != nil {
		return x.SupportedVersions
	}
	return nil
}

// HandshakeResponse publishes connection-level limits selected by the server.
type HandshakeResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion     uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	HeartbeatIntervalMs uint32                 `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	MaxFrameSize        uint32                 `protobuf:"varint,3,opt,name=max_frame_size,json=maxFrameSize,proto3" json:"max_frame_size,omitempty"`
	ConnectionId        string                 `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_net_proto_agp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{5}
}

func (x *HandshakeResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HandshakeResponse) GetHeartbeatIntervalMs() uint32 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *HandshakeResponse) GetMaxFrameSize() uint32 {
	if x != nil {
		return x.MaxFrameSize
	}
	return 0
}

func (x *HandshakeResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// HeartbeatRequest and HeartbeatResponse measure liveness without Actor routing.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTimeMs  int64                  `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_net_proto_agp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetClientTimeMs() int64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTimeMs  int64                  `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	ServerTimeMs  int64                  `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_net_proto_agp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetClientTimeMs() int64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

func (x *HeartbeatResponse) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

// CancelNotify cancels an in-flight Request on the same connection.
type CancelNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelNotify) Reset() {
	*x = CancelNotify{}
	mi := &file_net_proto_agp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelNotify) ProtoMessage() {}

func (x *CancelNotify) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelNotify.ProtoReflect.Descriptor instead.
func (*CancelNotify) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{8}
}

func (x *CancelNotify) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// KickNotify closes the connection and optionally permits client reconnection.
type KickNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReasonCode    int32                  `protobuf:"varint,1,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Reconnectable bool                   `protobuf:"varint,3,opt,name=reconnectable,proto3" json:"reconnectable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickNotify) Reset() {
	*x = KickNotify{}
	mi := &file_net_proto_agp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickNotify) ProtoMessage() {}

func (x *KickNotify) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickNotify.ProtoReflect.Descriptor instead.
func (*KickNotify) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{9}
}

func (x *KickNotify) GetReasonCode() int32 {
	if x != nil {
		return x.ReasonCode
	}
	return 0
}

func (x *KickNotify) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KickNotify) GetReconnectable() bool {
	if x != nil {
		return x.Reconnectable
	}
	return false
}

// GoAwayNotify is used during graceful server shutdown.
type GoAwayNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReasonCode    int32                  `protobuf:"varint,1,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	RetryAfterMs  uint32                 `protobuf:"varint,2,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoAwayNotify) Reset() {
	*x = GoAwayNotify{}
	mi := &file_net_proto_agp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoAwayNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoAwayNotify) ProtoMessage() {}

func (x *GoAwayNotify) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoAwayNotify.ProtoReflect.Descriptor instead.
func (*GoAwayNotify) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{10}
}

func (x *GoAwayNotify) GetReasonCode() int32 {
	if x != nil {
		return x.ReasonCode
	}
	return 0
}

func (x *GoAwayNotify) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

// HTTPError is the stable error body returned by the curl/HTTP adapter.
type HTTPError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPError) Reset() {
	*x = HTTPError{}
	mi := &file_net_proto_agp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPError) ProtoMessage() {}

func (x *HTTPError) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_agp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPError.ProtoReflect.Descriptor instead.
func (*HTTPError) Descriptor() ([]byte, []int) {
	return file_net_proto_agp_proto_rawDescGZIP(), []int{11}
}

func (x *HTTPError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HTTPError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HTTPError) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_net_proto_agp_proto protoreflect.FileDescriptor

const file_net_proto_agp_proto_rawDesc = "" +
	"\n" +
	"\x13net/proto/agp.proto\x12\x13actorgo.protocol.v1\"\xd8\x02\n" +
	"\x06Packet\x128\n" +
	"\arequest\x18\x01 \x01(\v2\x1c.actorgo.protocol.v1.RequestH\x00R\arequest\x12;\n" +
	"\bresponse\x18\x02 \x01(\v2\x1d.actorgo.protocol.v1.ResponseH\x00R\bresponse\x125\n" +
	"\x06notify\x18\x03 \x01(\v2\x1b.actorgo.protocol.v1.NotifyH\x00R\x06notify\x12E\n" +
	"\bmetadata\x18\x04 \x03(\v2).actorgo.protocol.v1.Packet.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\x05R\x05codec\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\x06\n" +
	"\x04kind\"x\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x1b\n" +
	"\tmethod_id\x18\x02 \x01(\rR\bmethodId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"k\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"9\n" +
	"\x06Notify\x12\x1b\n" +
	"\tmethod_id\x18\x01 \x01(\rR\bmethodId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\"A\n" +
	"\x10HandshakeRequest\x12-\n" +
	"\x12supported_versions\x18\x01 \x03(\rR\x11supportedVersions\"\xbd\x01\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\rR\x13heartbeatIntervalMs\x12$\n" +
	"\x0emax_frame_size\x18\x03 \x01(\rR\fmaxFrameSize\x12#\n" +
	"\rconnection_id\x18\x04 \x01(\tR\fconnectionId\"8\n" +
	"\x10HeartbeatRequest\x12$\n" +
	"\x0eclient_time_ms\x18\x01 \x01(\x03R\fclientTimeMs\"_\n" +
	"\x11HeartbeatResponse\x12$\n" +
	"\x0eclient_time_ms\x18\x01 \x01(\x03R\fclientTimeMs\x12$\n" +
	"\x0eserver_time_ms\x18\x02 \x01(\x03R\fserverTimeMs\"-\n" +
	"\fCancelNotify\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\"k\n" +
	"\n" +
	"KickNotify\x12\x1f\n" +
	"\vreason_code\x18\x01 \x01(\x05R\n" +
	"reasonCode\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12$\n" +
	"\rreconnectable\x18\x03 \x01(\bR\rreconnectable\"U\n" +
	"\fGoAwayNotify\x12\x1f\n" +
	"\vreason_code\x18\x01 \x01(\x05R\n" +
	"reasonCode\x12$\n" +
	"\x0eretry_after_ms\x18\x02 \x01(\rR\fretryAfterMs\"X\n" +
	"\tHTTPError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId*\xf5\x02\n" +
	"\n" +
	"StatusCode\x12\r\n" +
	"\tSTATUS_OK\x10\x00\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x01\x12\x1b\n" +
	"\x17STATUS_INVALID_ARGUMENT\x10\x02\x12\x1c\n" +
	"\x18STATUS_DEADLINE_EXCEEDED\x10\x03\x12\x14\n" +
	"\x10STATUS_NOT_FOUND\x10\x04\x12\x19\n" +
	"\x15STATUS_ALREADY_EXISTS\x10\x05\x12\x1c\n" +
	"\x18STATUS_PERMISSION_DENIED\x10\x06\x12\x1a\n" +
	"\x16STATUS_UNAUTHENTICATED\x10\a\x12\x1d\n" +
	"\x19STATUS_RESOURCE_EXHAUSTED\x10\b\x12\x1e\n" +
	"\x1aSTATUS_FAILED_PRECONDITION\x10\t\x12\x12\n" +
	"\x0eSTATUS_ABORTED\x10\n" +
	"\x12\x13\n" +
	"\x0fSTATUS_INTERNAL\x10\v\x12\x16\n" +
	"\x12STATUS_UNAVAILABLE\x10\f\x12\x1c\n" +
	"\x18STATUS_UNSUPPORTED_MEDIA\x10\rB2Z0github.com/actorgo-game/actorgo/net/proto;cprotob\x06proto3"

var (
	file_net_proto_agp_proto_rawDescOnce sync.Once
	file_net_proto_agp_proto_rawDescData []byte
)

func file_net_proto_agp_proto_rawDescGZIP() []byte {
	file_net_proto_agp_proto_rawDescOnce.Do(func() {
		file_net_proto_agp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_net_proto_agp_proto_rawDesc), len(file_net_proto_agp_proto_rawDesc)))
	})
	return file_net_proto_agp_proto_rawDescData
}

var file_net_proto_agp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_net_proto_agp_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_net_proto_agp_proto_goTypes = []any{
	(StatusCode)(0),           // 0: actorgo.protocol.v1.StatusCode
	(*Packet)(nil),            // 1: actorgo.protocol.v1.Packet
	(*Request)(nil),           // 2: actorgo.protocol.v1.Request
	(*Response)(nil),          // 3: actorgo.protocol.v1.Response
	(*Notify)(nil),            // 4: actorgo.protocol.v1.Notify
	(*HandshakeRequest)(nil),  // 5: actorgo.protocol.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 6: actorgo.protocol.v1.HandshakeResponse
	(*HeartbeatRequest)(nil),  // 7: actorgo.protocol.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 8: actorgo.protocol.v1.HeartbeatResponse
	(*CancelNotify)(nil),      // 9: actorgo.protocol.v1.CancelNotify
	(*KickNotify)(nil),        // 10: actorgo.protocol.v1.KickNotify
	(*GoAwayNotify)(nil),      // 11: actorgo.protocol.v1.GoAwayNotify
	(*HTTPError)(nil),         // 12: actorgo.protocol.v1.HTTPError
	nil,                       // 13: actorgo.protocol.v1.Packet.MetadataEntry
}
var file_net_proto_agp_proto_depIdxs = []int32{
	2,  // 0: actorgo.protocol.v1.Packet.request:type_name -> actorgo.protocol.v1.Request
	3,  // 1: actorgo.protocol.v1.Packet.response:type_name -> actorgo.protocol.v1.Response
	4,  // 2: actorgo.protocol.v1.Packet.notify:type_name -> actorgo.protocol.v1.Notify
	13, // 3: actorgo.protocol.v1.Packet.metadata:type_name -> actorgo.protocol.v1.Packet.MetadataEntry
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_net_proto_agp_proto_init() }
func file_net_proto_agp_proto_init() {
	if File_net_proto_agp_proto != nil {
		return
	}
	file_net_proto_agp_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_Request)(nil),
		(*Packet_Response)(nil),
		(*Packet_Notify)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_net_proto_agp_proto_rawDesc), len(file_net_proto_agp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_net_proto_agp_proto_goTypes,
		DependencyIndexes: file_net_proto_agp_proto_depIdxs,
		EnumInfos:         file_net_proto_agp_proto_enumTypes,
		MessageInfos:      file_net_proto_agp_proto_msgTypes,
	}.Build()
	File_net_proto_agp_proto = out.File
	file_net_proto_agp_proto_goTypes = nil
	file_net_proto_agp_proto_depIdxs = nil
}
