// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.15.8
// source: net/proto/cluster_message.proto

package cproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgType identifies the Actor operation carried between nodes.
type MsgType int32

const (
	MsgType_REQUEST  MsgType = 0
	MsgType_RESPONSE MsgType = 1
	MsgType_NOTIFY   MsgType = 2
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "REQUEST",
		1: "RESPONSE",
		2: "NOTIFY",
	}
	MsgType_value = map[string]int32{
		"REQUEST":  0,
		"RESPONSE": 1,
		"NOTIFY":   2,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_net_proto_cluster_message_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_net_proto_cluster_message_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_net_proto_cluster_message_proto_rawDescGZIP(), []int{0}
}

// ClusterMessage is the protobuf-only NATS message. payload uses codec, matching
// the original AGP or HTTP request body encoding.
type ClusterMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      uint64                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MsgType        MsgType                `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3,enum=actorgo.cluster.v1.MsgType" json:"msg_type,omitempty"`
	RequestId      uint32                 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MethodId       uint32                 `protobuf:"varint,4,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,5,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"` // Absolute deadline preserves one budget across hops.
	TargetPath     string                 `protobuf:"bytes,6,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`                // Optional; only used for an explicit child Actor.
	Session        *Session               `protobuf:"bytes,7,opt,name=session,proto3" json:"session,omitempty"`                                        // Snapshot of caller session; same layout as local Session.
	Metadata       map[string][]byte      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Codec          int32                  `protobuf:"varint,9,opt,name=codec,proto3" json:"codec,omitempty"`
	Payload        []byte                 `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	Code           int32                  `protobuf:"varint,11,opt,name=code,proto3" json:"code,omitempty"`      // Response status; zero for requests and notifications.
	Message        string                 `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"` // Response error text.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterMessage) Reset() {
	*x = ClusterMessage{}
	mi := &file_net_proto_cluster_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage) ProtoMessage() {}

func (x *ClusterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_cluster_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage.ProtoReflect.Descriptor instead.
func (*ClusterMessage) Descriptor() ([]byte, []int) {
	return file_net_proto_cluster_message_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterMessage) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ClusterMessage) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_REQUEST
}

func (x *ClusterMessage) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ClusterMessage) GetMethodId() uint32 {
	if x != nil {
		return x.MethodId
	}
	return 0
}

func (x *ClusterMessage) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

func (x *ClusterMessage) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *ClusterMessage) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ClusterMessage) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClusterMessage) GetCodec() int32 {
	if x != nil {
		return x.Codec
	}
	return 0
}

func (x *ClusterMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClusterMessage) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ClusterMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_net_proto_cluster_message_proto protoreflect.FileDescriptor

const file_net_proto_cluster_message_proto_rawDesc = "" +
	"\n" +
	"\x1fnet/proto/cluster_message.proto\x12\x12actorgo.cluster.v1\x1a\x15net/proto/proto.proto\"\x88\x04\n" +
	"\x0eClusterMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x04R\tmessageId\x126\n" +
	"\bmsg_type\x18\x02 \x01(\x0e2\x1b.actorgo.cluster.v1.MsgTypeR\amsgType\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\rR\trequestId\x12\x1b\n" +
	"\tmethod_id\x18\x04 \x01(\rR\bmethodId\x12(\n" +
	"\x10deadline_unix_ms\x18\x05 \x01(\x03R\x0edeadlineUnixMs\x12\x1f\n" +
	"\vtarget_path\x18\x06 \x01(\tR\n" +
	"targetPath\x12)\n" +
	"\asession\x18\a \x01(\v2\x0f.cproto.SessionR\asession\x12L\n" +
	"\bmetadata\x18\b \x03(\v20.actorgo.cluster.v1.ClusterMessage.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05codec\x18\t \x01(\x05R\x05codec\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayload\x12\x12\n" +
	"\x04code\x18\v \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01J\x04\b\r\x10\x0e*0\n" +
	"\aMsgType\x12\v\n" +
	"\aREQUEST\x10\x00\x12\f\n" +
	"\bRESPONSE\x10\x01\x12\n" +
	"\n" +
	"\x06NOTIFY\x10\x02B2Z0github.com/actorgo-game/actorgo/net/proto;cprotob\x06proto3"

var (
	file_net_proto_cluster_message_proto_rawDescOnce sync.Once
	file_net_proto_cluster_message_proto_rawDescData []byte
)

func file_net_proto_cluster_message_proto_rawDescGZIP() []byte {
	file_net_proto_cluster_message_proto_rawDescOnce.Do(func() {
		file_net_proto_cluster_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_net_proto_cluster_message_proto_rawDesc), len(file_net_proto_cluster_message_proto_rawDesc)))
	})
	return file_net_proto_cluster_message_proto_rawDescData
}

var file_net_proto_cluster_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_net_proto_cluster_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_net_proto_cluster_message_proto_goTypes = []any{
	(MsgType)(0),           // 0: actorgo.cluster.v1.MsgType
	(*ClusterMessage)(nil), // 1: actorgo.cluster.v1.ClusterMessage
	nil,                    // 2: actorgo.cluster.v1.ClusterMessage.MetadataEntry
	(*Session)(nil),        // 3: cproto.Session
}
var file_net_proto_cluster_message_proto_depIdxs = []int32{
	0, // 0: actorgo.cluster.v1.ClusterMessage.msg_type:type_name -> actorgo.cluster.v1.MsgType
	3, // 1: actorgo.cluster.v1.ClusterMessage.session:type_name -> cproto.Session
	2, // 2: actorgo.cluster.v1.ClusterMessage.metadata:type_name -> actorgo.cluster.v1.ClusterMessage.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_net_proto_cluster_message_proto_init() }
func file_net_proto_cluster_message_proto_init() {
	if File_net_proto_cluster_message_proto != nil {
		return
	}
	file_net_proto_proto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_net_proto_cluster_message_proto_rawDesc), len(file_net_proto_cluster_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_net_proto_cluster_message_proto_goTypes,
		DependencyIndexes: file_net_proto_cluster_message_proto_depIdxs,
		EnumInfos:         file_net_proto_cluster_message_proto_enumTypes,
		MessageInfos:      file_net_proto_cluster_message_proto_msgTypes,
	}.Build()
	File_net_proto_cluster_message_proto = out.File
	file_net_proto_cluster_message_proto_goTypes = nil
	file_net_proto_cluster_message_proto_depIdxs = nil
}
