// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: net/proto/proto.proto

package cproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type I32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I32) Reset() {
	*x = I32{}
	mi := &file_net_proto_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I32) ProtoMessage() {}

func (x *I32) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I32.ProtoReflect.Descriptor instead.
func (*I32) Descriptor() ([]byte, []int) {
	return file_net_proto_proto_proto_rawDescGZIP(), []int{0}
}

func (x *I32) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_net_proto_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_net_proto_proto_proto_rawDescGZIP(), []int{1}
}

func (x *NodeID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// member data
type Member struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeID           string                 `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`                                                                               // node id
	NodeType         string                 `protobuf:"bytes,2,opt,name=nodeType,proto3" json:"nodeType,omitempty"`                                                                           // node type
	Address          string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                                                             // rpc ip address
	Settings         map[string]string      `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // node settings data
	LastAt           int64                  `protobuf:"varint,5,opt,name=lastAt,proto3" json:"lastAt,omitempty"`                                                                              // last check time
	HeartbeatTimeout int64                  `protobuf:"varint,6,opt,name=heartbeatTimeout,proto3" json:"heartbeatTimeout,omitempty"`                                                          // The heartbeat timeout period (in milliseconds) for custom node configuration
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_net_proto_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_net_proto_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Member) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *Member) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Member) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Member) GetLastAt() int64 {
	if x != nil {
		return x.LastAt
	}
	return 0
}

func (x *Member) GetHeartbeatTimeout() int64 {
	if x != nil {
		return x.HeartbeatTimeout
	}
	return 0
}

// member list data
type MemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Member              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	mi := &file_net_proto_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_net_proto_proto_proto_rawDescGZIP(), []int{3}
}

func (x *MemberList) GetList() []*Member {
	if x != nil {
		return x.List
	}
	return nil
}

// Session contains connection/user state only. Request IDs never live here.
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`                                                                             // session unique id
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                                                                            // user id
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`                                                                               // ip address
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // extend data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_net_proto_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_net_proto_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_net_proto_proto_proto_rawDescGZIP(), []int{4}
}

func (x *Session) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *Session) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Session) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Session) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_net_proto_proto_proto protoreflect.FileDescriptor

const file_net_proto_proto_proto_rawDesc = "" +
	"\n" +
	"\x15net/proto/proto.proto\x12\x06cproto\"\x1b\n" +
	"\x03I32\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"\x1e\n" +
	"\x06NodeID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x91\x02\n" +
	"\x06Member\x12\x16\n" +
	"\x06nodeID\x18\x01 \x01(\tR\x06nodeID\x12\x1a\n" +
	"\bnodeType\x18\x02 \x01(\tR\bnodeType\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x128\n" +
	"\bsettings\x18\x04 \x03(\v2\x1c.cproto.Member.SettingsEntryR\bsettings\x12\x16\n" +
	"\x06lastAt\x18\x05 \x01(\x03R\x06lastAt\x12*\n" +
	"\x10heartbeatTimeout\x18\x06 \x01(\x03R\x10heartbeatTimeout\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\n" +
	"MemberList\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.cproto.MemberR\x04list\"\xa5\x01\n" +
	"\aSession\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12-\n" +
	"\x04data\x18\x04 \x03(\v2\x19.cproto.Session.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B2Z0github.com/actorgo-game/actorgo/net/proto;cprotob\x06proto3"

var (
	file_net_proto_proto_proto_rawDescOnce sync.Once
	file_net_proto_proto_proto_rawDescData []byte
)

func file_net_proto_proto_proto_rawDescGZIP() []byte {
	file_net_proto_proto_proto_rawDescOnce.Do(func() {
		file_net_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_net_proto_proto_proto_rawDesc), len(file_net_proto_proto_proto_rawDesc)))
	})
	return file_net_proto_proto_proto_rawDescData
}

var file_net_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_net_proto_proto_proto_goTypes = []any{
	(*I32)(nil),        // 0: cproto.I32
	(*NodeID)(nil),     // 1: cproto.NodeID
	(*Member)(nil),     // 2: cproto.Member
	(*MemberList)(nil), // 3: cproto.MemberList
	(*Session)(nil),    // 4: cproto.Session
	nil,                // 5: cproto.Member.SettingsEntry
	nil,                // 6: cproto.Session.DataEntry
}
var file_net_proto_proto_proto_depIdxs = []int32{
	5, // 0: cproto.Member.settings:type_name -> cproto.Member.SettingsEntry
	2, // 1: cproto.MemberList.list:type_name -> cproto.Member
	6, // 2: cproto.Session.data:type_name -> cproto.Session.DataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_net_proto_proto_proto_init() }
func file_net_proto_proto_proto_init() {
	if File_net_proto_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_net_proto_proto_proto_rawDesc), len(file_net_proto_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_net_proto_proto_proto_goTypes,
		DependencyIndexes: file_net_proto_proto_proto_depIdxs,
		MessageInfos:      file_net_proto_proto_proto_msgTypes,
	}.Build()
	File_net_proto_proto_proto = out.File
	file_net_proto_proto_proto_goTypes = nil
	file_net_proto_proto_proto_depIdxs = nil
}
