syntax = "proto3";

option go_package = "github.com/actorgo-game/actorgo/net/proto;cproto";

package cproto;

message I32 { int32 value = 1; }
message NodeID { string value = 1; }

// member data
message Member {
  string nodeID = 1;                    // node id
  string nodeType = 2;                  // node type
  string address = 3;                   // rpc ip address
  map<string, string> settings = 4;     // node settings data
  int64 lastAt = 5;                     // last check time
  int64 heartbeatTimeout = 6;           // The heartbeat timeout period (in milliseconds) for custom node configuration
  //map<string, int32> routes = 5;       // route list key:route name,value:status 0.enable 1.disable
}

// member list data
message MemberList { repeated Member list = 1; }

// Session contains connection/user state only. Request IDs never live here.
message Session {
  string sid = 1;                       // session unique id
  int64 uid = 2;                        // user id
  string ip = 3;                        // ip address
  map<string, string> data = 4;         // extend data
}
